site_name: PasarGuard Documentation
repo_url: https://github.com/PasarGuard/panel
repo_name: PasarGuard/panel
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PasarGuard
    - icon: material/file-document
      link: https://github.com/PasarGuard/docs

theme:
  name: material
  language: en
  logo: assets/logos/white.png
  favicon: assets/logos/white.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode (default)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
          nav_translations:
            Home: Home
            Node: Node
            Overview: Overview
            Installation: Installation
            API: API
            Environments: Environments
            Libraries: Libraries
            SSL: SSL

        - locale: fa
          name: فارسی  
          build: true
          nav_translations:
            Home: خانه
            Node: نود
            Overview: نمای کلی
            Installation: نصب
            API: API
            Environments: متغیر ها
            Libraries: کتابخانه‌ها
            SSL: SSL

        - locale: ru
          name: Русский
          build: true  
          nav_translations:
            Home: Главная
            Node: Узел
            Overview: Обзор
            Installation: Установка
            API: API
            Environments: Среды
            Libraries: Библиотеки
            SSL: SSL

        - locale: zh
          name: Chinese
          build: true
          nav_translations:
            Home: 首页
            Node: 节点
            Overview: 概览
            Installation: 安装
            API: API
            Environments: 环境
            Libraries: 库
            SSL: SSL

nav:
  - Home: index.md
  - Node:
    - Overview: node/overview.md
    - Installation: node/installation.md
    - Environments: node/environments.md
    - API: node/api.md
    - Libraries: node/libraries.md
    - SSL: node/ssl.md

extra_css:
  - stylesheets/extra.css
